import React from "react";
import { Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./shared.styles";

export interface PartialPaymentData {
  code: string;
  bookingCode: string;
  orderCode: string;
  serviceName: string;
  totalAmount: string | null;
  paidAmount: string | null;
  remainingAmount: string | null;
  currency: string | null;
  paymentStatus: string | null;
}

export function PartialPaymentTemplate({ data }: { data: PartialPaymentData }) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>TRAVELHUB PARTIAL PAYMENT DOCUMENT</Text>
        <Text style={styles.subtitle}>Payment State Confirmation</Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Document Code</Text>
          <Text style={styles.value}>{data.code}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Booking Reference</Text>
          <Text style={styles.value}>{data.bookingCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Order Reference</Text>
          <Text style={styles.value}>{data.orderCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Service</Text>
          <Text style={styles.value}>{data.serviceName}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Payment Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Total Amount</Text>
          <Text style={styles.value}>
            {data.totalAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Amount Paid</Text>
          <Text style={styles.value}>
            {data.paidAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Remaining Balance</Text>
          <Text style={styles.value}>
            {data.remainingAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Status</Text>
          <Text style={styles.value}>{data.paymentStatus ?? "N/A"}</Text>
        </View>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          This document reflects the current payment state on the TravelHub platform. It is NOT an
          invoice, fiscal receipt, or supplier document.
        </Text>
        <Text style={styles.disclaimer}>
          Document generated by TravelHub. For inquiries, contact your travel agent or
          support@travelhub.com.
        </Text>
      </View>
    </Page>
  );
}
