import React from "react";
import { Page, Text, View } from "@react-pdf/renderer";
import { styles, colors } from "./shared.styles";

export interface RefundData {
  code: string;
  bookingCode: string;
  orderCode: string;
  originalPaidAmount: string | null;
  refundAmount: string | null;
  refundedAmount: string | null;
  currency: string | null;
  paymentStatus: string | null;
  refundDate: string | null;
  refundCode: string | null;
}

export function RefundTemplate({ data }: { data: RefundData }) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>TRAVELHUB REFUND DOCUMENT</Text>
        <Text style={styles.subtitle}>Refund Processing Confirmation</Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Document Code</Text>
          <Text style={styles.value}>{data.code}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Booking Reference</Text>
          <Text style={styles.value}>{data.bookingCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Order Reference</Text>
          <Text style={styles.value}>{data.orderCode}</Text>
        </View>
        {data.refundCode && (
          <View style={styles.row}>
            <Text style={styles.label}>Refund Reference</Text>
            <Text style={styles.value}>{data.refundCode}</Text>
          </View>
        )}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Refund Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Original Paid Amount</Text>
          <Text style={styles.value}>
            {data.originalPaidAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>This Refund Amount</Text>
          <Text style={styles.value}>
            {data.refundAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total Refunded</Text>
          <Text style={styles.value}>
            {data.refundedAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Status</Text>
          <Text style={styles.value}>{data.paymentStatus ?? "N/A"}</Text>
        </View>
        {data.refundDate && (
          <View style={styles.row}>
            <Text style={styles.label}>Refund Date</Text>
            <Text style={styles.value}>{data.refundDate}</Text>
          </View>
        )}
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          This document confirms refund processing on the TravelHub platform. It is NOT a fiscal
          receipt or bank confirmation. Actual refund arrival depends on your payment provider.
        </Text>
        <Text style={styles.disclaimer}>
          Document generated by TravelHub. For inquiries, contact your travel agent or
          support@travelhub.com.
        </Text>
      </View>
    </Page>
  );
}
