import React from "react";
import { Page, Text, View } from "@react-pdf/renderer";
import { styles, colors } from "./shared.styles";

export interface VoucherData {
  code: string;
  bookingCode: string;
  orderCode: string;
  serviceName: string;
  serviceDate: string | null;
  serviceTime: string | null;
  serviceTimeZone: string | null;
  totalAmount: string | null;
  paidAmount: string | null;
  currency: string | null;
  paymentStatus: string | null;
  travelers: Array<{
    firstName: string;
    lastName: string;
    birthDate: string | null;
    citizenship: string | null;
    gender: string | null;
    passportNumber: string | null;
    passportExpiry: string | null;
  }>;
}

export function VoucherTemplate({ data }: { data: VoucherData }) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>TRAVELHUB VOUCHER</Text>
        <Text style={styles.subtitle}>Platform Confirmation Document</Text>
      </View>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Voucher Code</Text>
          <Text style={styles.value}>{data.code}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Booking Reference</Text>
          <Text style={styles.value}>{data.bookingCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Order Reference</Text>
          <Text style={styles.value}>{data.orderCode}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Service</Text>
          <Text style={styles.value}>{data.serviceName}</Text>
        </View>
        {data.serviceDate && (
          <View style={styles.row}>
            <Text style={styles.label}>Service Date</Text>
            <Text style={styles.value}>
              {data.serviceDate}
              {data.serviceTime ? ` ${data.serviceTime}` : ""}
              {data.serviceTimeZone ? ` (${data.serviceTimeZone})` : ""}
            </Text>
          </View>
        )}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Payment Summary</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Total Amount</Text>
          <Text style={styles.value}>
            {data.totalAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Amount Paid</Text>
          <Text style={styles.value}>
            {data.paidAmount ?? "N/A"} {data.currency ?? ""}
          </Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Balance</Text>
          <Text style={styles.value}>0.00 {data.currency ?? ""}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Status</Text>
          <Text style={styles.value}>{data.paymentStatus ?? "N/A"}</Text>
        </View>
      </View>

      {data.travelers.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Travelers</Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderText, { flex: 2 }]}>Name</Text>
            <Text style={[styles.tableHeaderText, { flex: 1 }]}>Citizenship</Text>
            <Text style={[styles.tableHeaderText, { flex: 1 }]}>Gender</Text>
          </View>
          {data.travelers.map((t, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={[styles.tableCell, { flex: 2 }]}>
                {t.firstName} {t.lastName}
              </Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{t.citizenship ?? "—"}</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{t.gender ?? "—"}</Text>
            </View>
          ))}
        </View>
      )}

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          This document is a TravelHub platform confirmation. It is NOT an airline ticket, hotel
          voucher, rail ticket, or supplier document. Seller Partner remains responsible for
          service-specific documentation.
        </Text>
        <Text style={styles.disclaimer}>
          Document generated by TravelHub. For inquiries, contact your travel agent or
          support@travelhub.com.
        </Text>
      </View>
    </Page>
  );
}
