"use client";

import { useRouter } from "next/navigation";
import FilterSidebar, { type FilterState } from "@/components/FilterSidebar";
import type { ServiceCategory } from "@/lib/filterConfig";

interface Props {
  type: string;
  filterCategory: ServiceCategory;
  path: string;
  sort: string | undefined;
}

export default function CatalogFilters({
  type,
  filterCategory,
  path,
  sort,
}: Props) {
  const router = useRouter();

  /** Build URLSearchParams from FilterState (generated by FilterSidebar) */
  const buildUrl = (fs: FilterState) => {
    const p = new URLSearchParams();
    if (sort && sort !== "popular") p.set("sort", sort);

    // Countries
    const countriesArr = fs._countries as string[] | undefined;
    if (countriesArr) countriesArr.forEach((c) => p.append("country", c));

    // Cities
    const citiesArr = fs._cities as string[] | undefined;
    if (citiesArr) citiesArr.forEach((c) => p.append("city", c));

    // Price
    const price = fs._price as [number, number] | undefined;
    if (price) {
      if (price[0] > 0) p.set("minPrice", String(price[0]));
      if (price[1] < 10000) p.set("maxPrice", String(price[1]));
    }

    // Rating
    const rating = fs._rating as number | undefined;
    if (rating && rating > 0) p.set("minRating", String(rating));

    // Generic array filters (meal, stars, tourType, etc.)
    Object.entries(fs).forEach(([key, val]) => {
      if (key.startsWith("_") || !Array.isArray(val) || val.length === 0) return;
      (val as string[]).forEach((v) => p.append(key, v));
    });

    router.push(`${path}?${p.toString()}`);
  };

  return (
    <aside className="self-start">
      <FilterSidebar
        category={filterCategory}
        onFilterChange={buildUrl}
      />
    </aside>
  );
}
